# Generated by Django 5.2 on 2025-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_bookingsettings_availabletimeslot_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='availabletimeslot',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='BookingSettings',
        ),
        migrations.AddField(
            model_name='member',
            name='hall_or_hostel',
            field=models.CharField(default='HALL_HOSTEL', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_enrollment',
            field=models.CharField(default='2025', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='room_number',
            field=models.CharField(default='R10', max_length=20),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AvailableTimeSlot',
        ),
    ]
