# Generated by Django 5.2 on 2025-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_appointment_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hall_or_hostel',
            field=models.CharField(default='hall or hostel', max_length=100),
        ),
    ]
